# Copyright (c) 2024, The University of North Carolina at Chapel Hill All rights reserved.
# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

name: ES Lint the repo

# trigger event is on a pull request
on:
  workflow_dispatch:
  #push

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      
      # Check out the repository
      - uses: actions/checkout@v2

      # Install Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 20

      # Install your dependencies
      - run: npm ci

      # Run ESLint
      - uses: eslint/github-action@v0
