# Copyright (c) 2024, The University of North Carolina at Chapel Hill All rights reserved.
# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

name: ES Lint the repo

# trigger event is on a push or a pull request
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Use .npmrc
        uses: bduff9/use-npmrc@v2.0.0
        with:
          dot-npmrc: ${{ secrets.DOT_NPMRC }}
      - run: pwd
      - run: ls -al
      - run: cat .npmrc
      - run: npm ci
      - run: npm run lint
